services:
  back:
    image: ghcr.io/${GITHUB_REPOSITORY:-crypte/ardent}/back:${IMAGE_TAG:-latest}
    expose:
      - "8090"
    environment:
      - NODE_ENV=production
    volumes:
      # En prod, on utilise un volume Docker persistant
      - pb_data_prod:/pb/pb_data
    networks:
      - app-network
      - caddy-net

  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-crypte/ardent}/app:${IMAGE_TAG:-latest}
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
      - caddy-net

  landing:
    image: ghcr.io/${GITHUB_REPOSITORY:-crypte/ardent}/landing:${IMAGE_TAG:-latest}
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
      - caddy-net

volumes:
  pb_data_prod:

networks:
  caddy-net:
    external: true