services:
  backend:
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    volumes:
      # En prod, on utilise un volume Docker persistant
      - pb_data_prod:/pb/pb_data
    networks:
      - app-network
      - caddy-net

  app:
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    build:
      args:
        - VITE_PB_URL=${VITE_PB_URL}
        - VITE_LANDING_URL=${VITE_LANDING_URL}
    networks:
      - app-network
      - caddy-net

  landing:
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    build:
      args:
        - VITE_APP_URL=${VITE_APP_URL}
    networks:
      - app-network
      - caddy-net

volumes:
  pb_data_prod:

networks:
  caddy-net:
    external: true